Feature/structures mode
EKami/qupath pull request #13
Opened 2018-12-13 10:07 UTC by theanuradha

2018-12-13 11:29 UTC, godardt requested changes
Please implement the STRUCTURE_MODE fully before submitting a PR. If I merge now the feature will only work partially without the validation process.

2018-12-13 11:29 UTC, godardt commented on qupath-gui-fx/src/main/java/qupath/lib/gui/viewer/tools/PolygonEditTool.java
> +        boolean isLocked = ((PathAnnotationObject) pathObject).isLocked() || !checkIfActionValid(viewer.getSelectedObject());
How is this `checkIfActionValid` supposed to help for the structures mode?

2018-12-13 11:29 UTC, godardt commented on qupath-gui-fx/src/main/java/qupath/lib/gui/QuPathGUI.java
> +        STRUCTURES_MODE("Structures mode", 4),
The Structures mode stands between the Specialist and contractor mode so its ID should be `3` and the Specialist mode should now be `4`

2018-12-13 16:10 UTC, theanuradha commented on qupath-gui-fx/src/main/java/qupath/lib/gui/viewer/tools/PolygonEditTool.java
> +        boolean isLocked = ((PathAnnotationObject) pathObject).isLocked() || !checkIfActionValid(viewer.getSelectedObject());
this is for stop PolygonEditTool from edit ROI or Inflammation if mode is Contract

2018-12-14 10:13 UTC, godardt requested changes
Looks great! Only one thing to add: The "Create project" and "Import Mirax files from root path" buttons in Structure mode should be disabled (same as with the Contractor mode)

2018-12-17 09:00 UTC, godardt approved these changes
Perfect thanks :)

2018-12-17 09:01 UTC, merged